[build]
  command = "npm run build"
  publish = "dist" # Vite build çıktısını "dist" içine koyar
[build.environment]
SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
NODE_OPTIONS="--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
